[info]
relay_url = "<url>"
name = "depot"
description = "Nostr Relay inside Lume. Powered by nostr-rs-relay"
pubkey = ""
favicon = "favicon.ico"
relay_icon = "https://example.test/img.png"
#contact = "mailto:contact@example.com"

[diagnostics]
#tracing = false

[database]
engine = "sqlite"
data_directory = "."
max_conn = 8
min_conn = 0

[logging]
#folder_path = "./log"
#file_prefix = "nostr-relay"

[network]
address = "0.0.0.0"
port = 6090
#remote_ip_header = "x-forwarded-for"
#remote_ip_header = "cf-connecting-ip"
#ping_interval = 300

[options]
reject_future_seconds = 1800

[limits]
messages_per_sec = 10
subscriptions_per_min = 10
limit_scrapers = false

[authorization]
pubkey_whitelist = []
nip42_auth = true
nip42_dms = true

[verified_users]
mode = "passive"
#domain_blacklist = ["wellorder.net"]
#domain_whitelist = ["example.com"]
verify_expiration = "1 week"
#verify_update_frequency = "24 hours"
max_consecutive_failures = 3

[grpc]
# gRPC interfaces for externalized decisions and other extensions to
# functionality.
#
# Events can be authorized through an external service, by providing
# the URL below.  In the event the server is not accessible, events
# will be permitted.  The protobuf3 schema used is available in
# `proto/nauthz.proto`.
# event_admission_server = "http://[::1]:50051"

# If the event admission server denies writes
# in any case (excluding spam filtering).
# This is reflected in the relay information document.
# restricts_write = true

[pay_to_relay]
# Enable pay to relay
#enabled = false

# The cost to be admitted to relay
#admission_cost = 4200

# The cost in sats per post
#cost_per_event = 0

# Url of lnbits api
#node_url = "<node url>"

# LNBits api secret
#api_secret = "<ln bits api>"

# Nostr direct message on signup
#direct_message=false

# Terms of service
#terms_message = """
#This service (and supporting services) are provided "as is", without warranty of any kind, express or implied.
#
#By using this service, you agree:
#* Not to engage in spam or abuse the relay service
#* Not to disseminate illegal content
#* That requests to delete content cannot be guaranteed
#* To use the service in compliance with all applicable laws
#* To grant necessary rights to your content for unlimited time
#* To be of legal age and have capacity to use this service
#* That the service may be terminated at any time without notice
#* That the content you publish may be removed at any time without notice
#* To have your IP address collected to detect abuse or misuse
#* To cooperate with the relay to combat abuse or misuse
#* You may be exposed to content that you might find triggering or distasteful
#* The relay operator is not liable for content produced by users of the relay
#"""

# Whether or not new sign ups should be allowed
#sign_ups = false

# optional if `direct_message=false`
#secret_key = "<nostr nsec>"
